import { Car, Container, Hammer, Home, KeyRound, Landmark, ShieldCheck, Sparkles, Store, Truck, Users, Warehouse, Wrench } from "lucide-react";

export const LANDING_CATEGORY_CARDS = [
  { slug: "cars", title: "Car Rentals", icon: Car, copy: "Daily, weekly, and long-term vehicles for families, tourism, business, and errands." },
  { slug: "trucks", title: "Trucks", icon: Truck, copy: "Pickup, box, flatbed, refrigerated, and commercial trucks for moving and delivery." },
  { slug: "heavy-equipment", title: "Heavy Equipment", icon: Hammer, copy: "Excavators, loaders, forklifts, cranes, and jobsite machinery." },
  { slug: "small-tools-machines", title: "Tools", icon: Wrench, copy: "Power tools, compact machines, cleaning tools, and trade equipment." },
  { slug: "event-spaces", title: "Event Spaces", icon: Landmark, copy: "Venues, studios, halls, yards, restaurants, and meeting spaces." },
  { slug: "real-estate", title: "Real Estate", icon: Home, copy: "Rental, sale, lease, brokerage, and property discovery listings." },
  { slug: "storage-containers", title: "Storage", icon: Container, copy: "Containers, lockers, portable storage, cold storage, and jobsite space." },
  { slug: "specialty-assets", title: "Specialty Assets", icon: Sparkles, copy: "Generators, boats, stages, lighting, agriculture assets, and other uncommon rentals." },
];

export const CATEGORY_PRODUCT_CONTENT = {
  cars: {
    title: "Car Rentals",
    eyebrow: "RentasHub Car Rentals",
    description: "Book trusted cars for airport runs, business travel, family days, tourism, and flexible long-term mobility.",
    icon: Car,
    heroImage: "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=1400&q=80",
    benefits: ["Flexible daily and weekly rates", "Supplier trust indicators", "Inspection-ready booking workflows", "Protection and payment readiness"],
    users: ["Tourists", "Families", "Business travelers", "Event teams"],
    supplierValue: "Turn idle vehicles into managed rental inventory with listing, booking, messaging, review, and trust workflows.",
    customerValue: "Compare locations, rates, supplier reputation, and availability before requesting a rental.",
    faqs: [
      ["Can customers pay live today?", "No. Payment workflows remain simulated until provider activation is completed."],
      ["Can cars be inspected?", "Yes. Check-in and check-out inspection flows are available for eligible bookings."],
      ["Can suppliers list cars for sale too?", "Yes. Listings can support rent, sale, rent-or-buy, and broker-assisted options."],
    ],
  },
  trucks: {
    title: "Truck Rentals",
    eyebrow: "RentasHub Truck Marketplace",
    description: "Find trucks for moving, delivery, construction logistics, commercial hauling, and short-term fleet support.",
    icon: Truck,
    heroImage: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&w=1400&q=80",
    benefits: ["Capacity and box-size fields", "Driver-included options", "Commercial-use labels", "Message-based quote workflows"],
    users: ["Movers", "Retailers", "Contractors", "Delivery teams"],
    supplierValue: "Show capacity, driver options, business use, location, and booking readiness in one workflow.",
    customerValue: "Filter by truck type, price, location, delivery/pickup options, and supplier reputation.",
    faqs: [
      ["Are driver-included rentals supported?", "Yes. Truck listings include a driver-included option."],
      ["Are commercial jobs supported?", "Yes. Commercial-use fields are part of the truck listing structure."],
      ["Does RentasHub process live freight payments?", "No. Real payment provider activation is still pending."],
    ],
  },
  "heavy-equipment": {
    title: "Heavy Equipment",
    eyebrow: "RentasHub Heavy Equipment",
    description: "Discover excavators, loaders, bulldozers, forklifts, cranes, and jobsite machinery with trust and inspection workflows.",
    icon: Hammer,
    heroImage: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1400&q=80",
    benefits: ["Operator-required controls", "Engine-hour tracking", "Inspection and damage notes", "Claims and dispute readiness"],
    users: ["Contractors", "Developers", "Farmers", "Infrastructure teams"],
    supplierValue: "Present equipment specs, operator rules, safety instructions, and trust signals clearly.",
    customerValue: "Compare equipment type, operating weight, availability, location, and supplier credibility.",
    faqs: [
      ["Can equipment require an operator?", "Yes. Heavy equipment listings include operator-required fields."],
      ["Are engine hours tracked?", "Yes. The inspection model includes engine-hour-ready fields."],
      ["Is insurance live?", "No. Protection and insurance workflows remain readiness/simulated until activation."],
    ],
  },
  "small-tools-machines": {
    title: "Tools & Machines",
    eyebrow: "RentasHub Tools",
    description: "Rent small tools, compact machines, cleaning equipment, and project gear for home, trade, and jobsite work.",
    icon: Wrench,
    heroImage: "https://images.unsplash.com/photo-1581147036324-c1c89c2c8b5c?auto=format&fit=crop&w=1400&q=80",
    benefits: ["Power-type fields", "Condition notes", "Accessory tracking", "Simple local booking workflow"],
    users: ["Homeowners", "Tradespeople", "Repair teams", "Small contractors"],
    supplierValue: "Package accessories, condition, usage instructions, and safety notes into clear rental listings.",
    customerValue: "Find tools by location, power type, price, condition, and supplier trust indicators.",
    faqs: [
      ["Can accessories be tracked?", "Yes. Tool and equipment flows include accessory fields."],
      ["Can damaged or missing accessories be recorded?", "Yes. Check-out and claim foundations support those notes."],
      ["Are deposits live?", "No. Deposit and escrow activation remains a future provider/legal step."],
    ],
  },
  "event-spaces": {
    title: "Event Spaces",
    eyebrow: "RentasHub Event Spaces",
    description: "Find halls, studios, restaurants, outdoor venues, conference rooms, and private spaces for planned events.",
    icon: Landmark,
    heroImage: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1400&q=80",
    benefits: ["Capacity and amenities", "Parking and noise rules", "Event type matching", "Message-first booking context"],
    users: ["Event planners", "Families", "Corporate teams", "Creators"],
    supplierValue: "Show space rules, amenities, capacity, parking, and event-fit information before inquiries arrive.",
    customerValue: "Compare space capacity, location, event type, rules, supplier profile, and availability.",
    faqs: [
      ["Can noise rules be listed?", "Yes. Event space listings include noise-rule fields."],
      ["Can bookings be requested?", "Yes. Booking requests are supported, with payments still simulated."],
      ["Are event contracts generated?", "No. Legal contract generation is not active."],
    ],
  },
  "real-estate": {
    title: "Real Estate",
    eyebrow: "RentasHub Real Estate",
    description: "Explore property rentals, leases, sales, brokerage-assisted opportunities, and short-term rental discovery.",
    icon: Home,
    heroImage: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1400&q=80",
    benefits: ["Bedrooms, bathrooms, and square footage", "Lease/sale/rental options", "Brokerage support", "Wanted request workflows"],
    users: ["Renters", "Property owners", "Brokers", "Relocation teams"],
    supplierValue: "Publish property details, rules, pricing, and brokerage intent without mixing into equipment workflows.",
    customerValue: "Search by location, property type, price, listing type, and supplier/business profile.",
    faqs: [
      ["Can properties be listed for sale?", "Yes. Sale and brokerage-assisted listing types are supported."],
      ["Does RentasHub handle legal conveyancing?", "No. Legal agreements and conveyancing are outside the current build."],
      ["Can customers post wanted requests?", "Yes. Wanted requests are supported for property and asset needs."],
    ],
  },
  "storage-containers": {
    title: "Storage & Containers",
    eyebrow: "RentasHub Storage",
    description: "Find storage units, secure lockers, shipping containers, portable storage, and jobsite container options.",
    icon: Warehouse,
    heroImage: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1400&q=80",
    benefits: ["Dimensions and access rules", "Security feature fields", "Private access notes", "Location-first discovery"],
    users: ["Retailers", "Movers", "Contractors", "Households"],
    supplierValue: "List dimensions, access windows, security features, and rules with clear supplier ownership.",
    customerValue: "Compare size, location, access, security, rate, and supplier trust signals before requesting storage.",
    faqs: [
      ["Can access rules be shown?", "Yes. Storage/container listings include access-rule fields."],
      ["Can private storage photos be uploaded?", "Storage is upload-ready, but real object storage is not active yet."],
      ["Can long-term storage be listed?", "Yes. Monthly and long-term rental types are supported."],
    ],
  },
  "specialty-assets": {
    title: "Specialty Assets",
    eyebrow: "RentasHub Specialty Assets",
    description: "List and discover uncommon assets such as boats, generators, stages, lighting, agriculture gear, and custom inventory.",
    icon: Sparkles,
    heroImage: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?auto=format&fit=crop&w=1400&q=80",
    benefits: ["Flexible category fields", "Broker and trade options", "AI listing helper", "Trust and review summaries"],
    users: ["Creators", "Farmers", "Production teams", "Specialty suppliers"],
    supplierValue: "Bring unusual inventory into a structured marketplace without forcing it into a standard category.",
    customerValue: "Use search, AI assistance, wanted requests, and marketplace filters to discover uncommon assets.",
    faqs: [
      ["Can unusual assets be listed?", "Yes. Specialty assets are designed for inventory that does not fit ordinary categories."],
      ["Can users trade or swap specialty assets?", "Yes. Trade, swap, and broker-assisted listing types exist."],
      ["Does RentasHub guarantee asset condition?", "No. Trust, inspection, claims, and reviews help support decisions, but live guarantees are not active."],
    ],
  },
};

export const LANDING_TRUST_BADGES = [
  { icon: ShieldCheck, label: "Trust Engine Ready", detail: "Local score and risk signal foundations." },
  { icon: KeyRound, label: "Auth Credential-Ready", detail: "Supabase mode waits for secure credentials." },
  { icon: Store, label: "Provider-Ready Payments", detail: "Simulation remains default until activation." },
  { icon: Warehouse, label: "Storage Ready", detail: "Supabase bucket plan is prepared." },
  { icon: Users, label: "Pilot Operations", detail: "Supplier, support, and moderation playbooks exist." },
  { icon: Hammer, label: "Escrow Readiness", detail: "No live funds held until legal/provider approval." },
];
