export const config = {
  port: Number(process.env.PORT || 4000),
  nodeEnv: process.env.NODE_ENV || "development",
  apiPrefix: process.env.API_PREFIX || "/api",
  authProvider: process.env.AUTH_PROVIDER || "local",
  authTokenSecret: process.env.AUTH_TOKEN_SECRET || "change-this-development-secret-before-real-use",
  databaseUrl: process.env.DATABASE_URL || "",
  paymentProvider: process.env.PAYMENT_PROVIDER || "placeholder",
  paymentMode: process.env.PAYMENT_MODE || "simulated",
  paymentPublicKey: process.env.PAYMENT_PUBLIC_KEY || "",
  paymentSecretKey: process.env.PAYMENT_SECRET_KEY || "",
  escrowProvider: process.env.ESCROW_PROVIDER || "placeholder",
  escrowApiKey: process.env.ESCROW_API_KEY || "",
  kycProvider: process.env.KYC_PROVIDER || "placeholder",
  insuranceProvider: process.env.INSURANCE_PROVIDER || "placeholder",
  notificationProvider: process.env.NOTIFICATION_PROVIDER || "placeholder",
  fileStorageProvider: process.env.FILE_STORAGE_PROVIDER || "local_placeholder",
  deploymentProvider: process.env.DEPLOYMENT_PROVIDER || "local",
  platformFeePercentage: Number(process.env.PLATFORM_FEE_PERCENTAGE || 10),
  payoutMode: process.env.PAYOUT_MODE || "simulated",
  appBaseUrl: process.env.APP_BASE_URL || "",
  corsOrigin: process.env.CORS_ORIGIN || "",
  requestAudit: String(process.env.ENABLE_REQUEST_AUDIT ?? "true") !== "false",
};
